function go = getTOARglobalOffset(obs, goScenario, goPlot)
% getTOARglobalOffset - Estimates global offset for TOAR ozone data
%
% Models the space/time global offset for TOAR-II ozone data following
% the same methodology as getAPglobalOffset.m
%
% SYNTAX:
%  
% go = getTOARglobalOffset(obs, goScenario, goPlot);
%
% INPUT :
%
% obs         structure containing TOAR observational data from getTOARobservationalData
% goScenario  scalar specifying global offset scenario 
%             0 zero, 1 flat, 2 domain wide, 3 regional, 4 local
%             default: 3
% goPlot      scalar indicating plotting level
%             0 no plots, 1 basic plots, 2 detailed plots, 3 comprehensive plots
%             default: 1
%
% OUTPUT :
% go   structure containing global offset:
%      go.logTransf      scalar   0 (no log transform for ozone)
%      go.scenario       scalar   global offset scenario
%      go.sMSraw         nMS x 2  original station coordinates
%      go.tMEraw         1 x nME  original time vector
%      go.msRaw          nMS x 1  raw spatial means
%      go.mtRaw          1 x nME  raw temporal means
%      go.sMS            nMSd x 2 densified spatial coordinates
%      go.tME            1 x nMEd densified time vector
%      go.ms             nMSd x 1 smoothed spatial means
%      go.mt             1 x nMEd smoothed temporal means
%      go.goParam        1 x 5    global offset parameters
%      go.densParam      1 x 6    densification parameters

if nargin < 1, error('obs structure required'); end
if nargin < 2, goScenario = 3; end
if nargin < 3, goPlot = 1; end

if isnumeric(obs), error('obs must be a structure from getTOARobservationalData'); end

% Create global offset directory
goDir = '2globalOffset';
if ~exist(goDir, 'dir')
    mkdir(goDir);
    fid = fopen(fullfile(goDir, '0readme.txt'), 'w');
    fprintf(fid, 'Global offset files for TOAR-II data analysis.\n');
    fprintf(fid, 'Generated by getTOARglobalOffset.m\n');
    fclose(fid);
end

% Set filename for saved results
goFile = sprintf('%s_go_%d.mat', obs.Zname, goScenario);

% Force re-estimation (set to 0 to use saved results)
forceGOestimation = 1;

if exist(fullfile(goDir, goFile), 'file') && ~forceGOestimation
    load(fullfile(goDir, goFile), 'go');
    fprintf('Loaded existing global offset from %s\n', fullfile(goDir, goFile));
else
    fprintf('Computing global offset for TOAR data (scenario %d)...\n', goScenario);
    
    % Set global offset parameters based on scenario
    switch goScenario
        case 0, goParam = [NaN NaN NaN NaN 0];  % Zero offset
        case 1, goParam = [10000 10000 10000 10000 0];  % Flat
        case 2, goParam = [180 5 50 20 0];      % Domain wide (global scale)
        case 3, goParam = [90 2 20 5 0];        % Regional
        case 4, goParam = [45 0.5 10 2 0];      % Local
    end
    
    % Set densification parameters
    inclvoronoi = 1;      % Include Voronoi vertices
    inclgrid = 1;         % Include regular grid
    nxpix = 40;           % X-direction pixels
    nypix = 25;           % Y-direction pixels
    densifytME = 1;       % Densify time
    tMEtimeStep = 1/12;   % Monthly time step
    densParam = [inclvoronoi inclgrid nxpix nypix densifytME tMEtimeStep];
    
    % Set spatial domain (global extent for TOAR data)
    axMS = [-180 180 -90 90];  % Global longitude/latitude range
    
    % Remove stations with insufficient data
    validStations = sum(~isnan(obs.Y), 2) >= 12; % At least 12 valid observations
    fprintf('Using %d stations with sufficient data (out of %d total)\n', ...
            sum(validStations), length(validStations));
    
    Y_filtered = obs.Y(validStations, :);
    sMS_filtered = obs.sMS(validStations, :);
    stationID_filtered = obs.stationID(validStations);
    
    % Calculate space/time mean using stmeanDensified
    [msRaw, mssd, mtRaw, mtsd, sMSd, tMEd] = stmeanDensified(...
        Y_filtered, sMS_filtered, stationID_filtered, obs.tME, goParam, densParam, axMS);
    
    % Handle zero scenario
    if goScenario == 0
        mssd = zeros(size(mssd));
        mtsd = zeros(size(mtsd));
    end
    
    % Build output structure
    go.logTransf = obs.logTransf;
    go.scenario = goScenario;
    go.sMSraw = sMS_filtered;
    go.tMEraw = obs.tME;
    go.msRaw = msRaw;
    go.mtRaw = mtRaw;
    go.sMS = sMSd;
    go.tME = tMEd;
    go.ms = mssd;
    go.mt = mtsd;
    go.goParam = goParam;
    go.densParam = densParam;
    
    % Save results
    save(fullfile(goDir, goFile), 'go');
    fprintf('Global offset saved to %s\n', fullfile(goDir, goFile));
end

% Generate plots if requested
if goPlot >= 1
    plotTOARglobalOffset(obs, go, goPlot);
end

end