function cov = getTOARcovariance(obs, go, covPlot)
% getTOARcovariance - Estimates space/time covariance for TOAR ozone data
%
% Models the space/time covariance of offset-removed TOAR ozone data
% following the methodology from getAPcov.m
%
% SYNTAX:
%  
% cov = getTOARcovariance(obs, go, covPlot)
%
% INPUT :
% 
% obs     structure from getTOARobservationalData
% go      structure from getTOARglobalOffset or scalar scenario number
% covPlot scalar for plotting: 0-no plot, 1-2D plots, 2-2D and 3D plots
%         default: 1
%
% OUTPUT :
% cov     structure containing experimental covariance and model:
%         cov.Zname       string  'OZONE_TOAR'
%         cov.Yname       string  variable name
%         cov.rLag        vector  spatial lags
%         cov.Cr          vector  experimental spatial covariance
%         cov.npr         vector  number of pairs for spatial covariance
%         cov.tLag        vector  temporal lags
%         cov.Ct          vector  experimental temporal covariance
%         cov.npt         vector  number of pairs for temporal covariance
%         cov.var         scalar  experimental variance
%         cov.covmodel    cell    covariance model specification
%         cov.covparam    cell    covariance parameters

if nargin < 1, error('obs structure required'); end
if nargin < 2, go = 3; end
if nargin < 3, covPlot = 1; end

if isnumeric(obs), error('obs must be structure from getTOARobservationalData'); end
if isnumeric(go), go = getTOARglobalOffset(obs, go, 0); end

% Create covariance directory
covDir = '3covariance';
if ~exist(covDir, 'dir')
    mkdir(covDir);
    fid = fopen(fullfile(covDir, '0readme.txt'), 'w');
    fprintf(fid, 'Covariance files for TOAR-II data analysis.\n');
    fprintf(fid, 'Generated by getTOARcovariance.m\n');
    fclose(fid);
end

% Set filename
covFile = sprintf('%s_cov_go%d.mat', obs.Zname, go.scenario);

% Force re-estimation (set to 0 to use saved results)
forceCOVestimation = 0;

if exist(fullfile(covDir, covFile), 'file') && ~forceCOVestimation
    load(fullfile(covDir, covFile), 'cov');
    fprintf('Loaded existing covariance from %s\n', fullfile(covDir, covFile));
else
    fprintf('Computing covariance for TOAR data...\n');
    
    % Remove global offset from data
    X = obs.Y - stmeaninterp(go.sMS, go.tME, go.ms, go.mt, obs.sMS, obs.tME);
    
    % Set up spatial and temporal lags for global data
    % Spatial lags in degrees (global scale)
    rLag = [0 0.5 1.0 2.0 5.0 10.0:5.0:30.0 40.0:10.0:90.0];
    rLagTol = [0 0.25 0.5 1.0 2.0 2.5*ones(1,5) 5.0*ones(1,6)];
    
    % Temporal lags in years
    tLag = [0:1/12:2 3:1:10];  % Monthly for first 2 years, then yearly
    tLagTol = [0.05*ones(1,25) 0.5*ones(1,8)];
    
    % Calculate experimental covariance
    fprintf('  Calculating spatial covariance...\n');
    [Cr, npr] = stcov(X, obs.sMS, obs.tME, X, obs.sMS, obs.tME, ...
                      rLag, rLagTol, 0, 0.1, {'coord2dist'}, 'kron');
    
    fprintf('  Calculating temporal covariance...\n');
    [Ct, npt] = stcov(X, obs.sMS, obs.tME, X, obs.sMS, obs.tME, ...
                      0, 0.001, tLag, tLagTol, {'coord2dist'}, 'kron');
    
    % Calculate variance
    v = var(X(~isnan(X)));
    
    % Set covariance model parameters for ozone (global scale)
    switch go.scenario
        case {0, 1}  % Zero or flat
            c01 = v * 0.6; ar1 = 50; at1 = 2;
            c02 = v * 0.4; ar2 = 5; at2 = 10;
        case 2       % Domain wide
            c01 = v * 0.5; ar1 = 30; at1 = 1;
            c02 = v * 0.5; ar2 = 3; at2 = 5;
        case 3       % Regional
            c01 = v * 0.4; ar1 = 20; at1 = 0.5;
            c02 = v * 0.6; ar2 = 2; at2 = 3;
        case 4       % Local
            c01 = v * 0.3; ar1 = 10; at1 = 0.25;
            c02 = v * 0.7; ar2 = 1; at2 = 1.5;
    end
    
    % Build covariance structure
    cov.Zname = obs.Zname;
    cov.Yname = obs.Yname;
    cov.rLag = rLag;
    cov.Cr = Cr;
    cov.npr = npr;
    cov.tLag = tLag;
    cov.Ct = Ct;
    cov.npt = npt;
    cov.var = v;
    cov.covmodel = {'exponentialC/exponentialC', 'exponentialC/exponentialC'};
    cov.covparam = {[c01 ar1 at1], [c02 ar2 at2]};
    
    % Save results
    save(fullfile(covDir, covFile), 'cov');
    fprintf('Covariance saved to %s\n', fullfile(covDir, covFile));
end

% Generate plots if requested
if covPlot >= 1
    plotTOARcovariance(cov, 'obs', obs, 'go', go, 'visible', 'on');
end

end